#!/home/nykimberly/anaconda3/bin/python3

def count_words(filepath):
    """Approximate number of words in provided file"""
    try:
        with open(filepath, encoding='utf-8') as f:
            contents = f.read()
    except FileNotFoundError:
        msg = filepath + " not found!"
        with open('fnf-files', 'a') as f:
            f.write(filepath + "\n")
        print(msg)
    else:
        words = contents.split()
        num_words = len(words)
        msg = filepath + " contains " + str(num_words) + " words!"
        print(msg)

count_words('literary-works/alice.txt')
count_words('literary-works/little_women.txt')
count_words('literary-works/kimberly.txt')
count_words('literary-works/moby_dick.txt')
