#! /usr/bin/env python3

"""Greppy: A grep-mock implementation with Python"""

import sys
import re
import argparse
import json

# Initialize parser with description
parser = argparse.ArgumentParser(
        description="Greppy is a CLI tool for grep-ish actions",
        add_help=False
)

parser.add_argument(
        "-c",
        action="store_true",
        dest="show_count",
        help="Show count of matches",
)

parser.add_argument(
        "-h",
        action="store_true",
        dest="suppress_filenames",
        help="Suppress showing filenames",
)

parser.add_argument(
        "-H",
        action="store_true",
        dest="show_filenames",
        help="Show filenames",
)

parser.add_argument(
        "--help",
        action="store_true",
        dest="show_help",
        help="Show help message",
)

parser.add_argument(
        "-i",
        action="store_true",
        dest="case_insensitive",
        help="Match regardless of case",
)


parser.add_argument(
        "-l",
        action="store_true",
        dest="files_only",
        help="Print only the filenames with matches",
)

parser.add_argument(
        "-o",
        action="store_true",
        dest="pattern_only",
        help="Print only the matching patterns",
)

parser.add_argument(
        "-v",
        action="store_true",
        dest="inverse",
        help="Print lines that do not match given pattern",
)

parser.add_argument(
        "pattern",
        type=str,
        help="Match pattern",
)

parser.add_argument(
        "filenames",
        type=str,
        nargs="*",
        help="Files to search",
)

if __name__ == "__main__":

    # Is there a way to catch the requirement error and allow users to just do
    # greppy --help without providing a pattern and file?
    args = parser.parse_args()

    # If -h specified, show help and exit
    if args.show_help:
        parser.print_help()
        exit(0)

    # Create re object
    if args.case_insensitive:
        args.pattern = "(?i)" + args.pattern

    pattern = re.compile(args.pattern)
